version: "3"

services:
  bw-listener:
    container_name: bw-listener
    image: bw-listener
    build: ./
    ports:
      - "8003:8003"
    expose:
      - "8003"
    networks:
      esnet:
    environment:
      - "SPRING_PROFILES_ACTIVE=standalone"

volumes:
  esdata1:
    driver: local

networks:
  esnet:
    driver: bridge
